<Project Sdk="Microsoft.NET.Sdk;Bannerlord.BuildResourcesLite.Sdk/1.2.1.38">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="GUI\Brushes\Diplomacy.xml" />
    <EmbeddedResource Include="GUI\Prefabs\Encyclopedia\EncyclopediaSubPages\EncyclopediaFactionPageInject.xml" />
    <EmbeddedResource Include="GUI\Prefabs\Encyclopedia\EncyclopediaSubPages\EncyclopediaHeroPageInject.xml" />
    <EmbeddedResource Include="GUI\Prefabs\Encyclopedia\EncyclopediaSubPages\FactionButtonInject.xml" />
    <EmbeddedResource Include="GUI\Prefabs\GrantFief\GrantFief.xml" />
    <EmbeddedResource Include="GUI\Prefabs\GrantFief\GrantFiefTuple.xml" />
    <EmbeddedResource Include="GUI\Prefabs\KingdomManagement\Clan\ClansPanel.xml" />
    <EmbeddedResource Include="GUI\Prefabs\KingdomManagement\Clan\DonateGold.xml" />
    <EmbeddedResource Include="GUI\Prefabs\KingdomManagement\Diplomacy\DiplomacyPanelButtons.xml" />
    <EmbeddedResource Include="GUI\Prefabs\KingdomManagement\Diplomacy\DiplomacyPanelCustom.xml" />
    <EmbeddedResource Include="GUI\Prefabs\KingdomManagement\Diplomacy\OverviewTab.xml" />
    <EmbeddedResource Include="GUI\Prefabs\KingdomManagement\Diplomacy\Relationship.xml" />
    <EmbeddedResource Include="GUI\Prefabs\KingdomManagement\Diplomacy\StatsTab.xml" />
    <EmbeddedResource Include="GUI\Prefabs\RebelFactions\RebelFactionDivider.xml" />
    <EmbeddedResource Include="GUI\Prefabs\RebelFactions\RebelFactionParticipant.xml" />
    <EmbeddedResource Include="GUI\Prefabs\RebelFactions\RebelFactions.xml" />
    <EmbeddedResource Include="GUI\Prefabs\RebelFactions\RebelFactionsItem.xml" />
    <EmbeddedResource Include="GUI\Prefabs\Standard\BasicDiplomacyButton.xml" />
    <EmbeddedResource Include="GUI\Prefabs\Standard\StaticDiplomacyButton.xml" />
    <EmbeddedResource Include="GUI\Prefabs\WarExhaustion\DetailWarView.xml" />
    <EmbeddedResource Include="GUI\Prefabs\WarExhaustion\WarExhaustionMapIndicator.xml" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ColorMinePortable" Version="2.0.4" />
    <PackageReference Include="Bannerlord.BUTR.Shared" Version="3.0.0.142">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Bannerlord.ModuleLoader.Injector" Version="1.0.1.50" />
    <PackageReference Include="Bannerlord.ModuleManager.Source" Version="6.0.247" />
    <PackageReference Include="Bannerlord.ButterLib" Version="2.11.1" IncludeAssets="compile" />
    <PackageReference Include="Bannerlord.MCM" Version="5.12.2" IncludeAssets="compile" />
    <PackageReference Include="Lib.Harmony" Version="2.4.2" IncludeAssets="compile" />
    <PackageReference Include="Bannerlord.UIExtenderEx" Version="2.13.2" IncludeAssets="compile" />
    <PackageReference Include="Harmony.Extensions" Version="3.2.0.77">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>